### ISSUE TITLE
MySQL Class Missing

### ISSUE THREAD

**Issue by coco0325** [CodeCrafter47/BungeeMail#14]
It seems that BungeeMail is not compatible with the latest version of Waterfall.
```
[10:02:06] [main/WARN] [BungeeMail]: MySQL DataSource class missing: com.mysql.jdbc.jdbc2.optional.MysqlDataSource.
[10:02:06] [main/WARN]: Exception encountered when loading plugin: BungeeMail
java.lang.RuntimeException: Failed to connect to MySql database
	at codecrafter47.bungeemail.MySQLBackend.setupDataSource(MySQLBackend.java:38) ~[?:?]
	at codecrafter47.bungeemail.MySQLBackend.<init>(MySQLBackend.java:20) ~[?:?]
	at codecrafter47.bungeemail.BungeeMail.onEnable(BungeeMail.java:79) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
```

**Comment by RedstoneFuture** [comment]
I can replicate this. Tested with `BungeeMail version 1.10 by CodeCrafter47` on `git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:1e7dff4:469`.
